In [2]:
from numpy import *
import operator
import numpy as np

输入的数据要求是numpy类型的
到时候先读取数据再转换一下

In [ ]:
def aknn(testdata,dataSet,labels,k):
    dataSize = dataSet.shape[0]
    diffMat = tile(testdata,(dataSize,1))-dataSet
    sqDiffMat = diffMat**2
    sqDistance = sqDiffMat.sum(axis=1)
    distance_list = [math.sqrt(i) for i in sqDistance]
    

In [51]:
def aa_knn(trainFeature,trainLabel,testFeature,testLabel,k):
    rows = testFeature.shape[0]
    cols = testFeature.shape[1]

    train_num = trainFeature.shape[0]
    dist = np.zeros(shape=(train_num))
    prediction = np.zeros(shape=(rows,trainLabel.shape[1]))

    for i in range(rows):
        test = testFeature[i,:]
        for j in range(train_num):
            train = trainFeature[j,:]
            V = test - train
            sqV = V**2
            sqDis = sqV.sum(axis=0)
            dist[j] = math.sqrt(sqDis)

        indice = dist.argsort()
        sort_dis = sorted(dist)
        sum_label = np.zeros(shape=trainLabel.shape[1])
        for l in range(k):
            sum_label = sum_label + trainLabel[indice[l],:]

        prediction[i,:] = sum_label/k
    
    idx = prediction.argmax(axis=1)
    prediction = (idx[:,None] == np.arange(prediction.shape[1])).astype(int)
    
    return prediction

In [4]:
file_feature = open("ldlFeature.txt",'r')

feature = []

for line in file_feature:
    one_fea = list(map(lambda x : float(x), line.split()))
    feature.append(one_fea)


In [5]:
file_label = open("ldlLabelAll.txt",'r')

label = []

for line in file_label:
    one_label = list(map(lambda x : float(x), line.split()))
    label.append(one_label)

In [19]:
trainFeature = array(feature[:70])
trainLabel = array(label[:70])

testFeature = array(feature[190:])

In [59]:
b = aa_knn(trainFeature,trainLabel,testFeature,6)

In [27]:
idx = b.argmax(axis=1)
out = (idx[:,None] == np.arange(b.shape[1])).astype(float)



In [48]:
file_ = open("ldlLabelAll.txt",'r')

binary_label = []

for line in file_:
    a = line.split()[:2]
    binary_label.append(a)

binary_label = array(binary_label)

idx = binary_label.argmax(axis=1)
binary_label = (idx[:,None] == np.arange(binary_label.shape[1])).astype(int)
    

In [60]:
print(b)

[[1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]]


In [50]:
file_w = open("binaryLabel.txt",'w')

for item in binary_label:
    
    file_w.write(str(item[0])+" "+ str(item[1])+"\n")

file_w.close()

In [56]:
test = array(label[190:])

In [57]:
idx = test.argmax(axis=1)
ground_truth = (idx[:,None] == np.arange(test.shape[1])).astype(int)

In [62]:
from sklearn import metrics

score = metrics.accuracy_score(b,ground_truth)

print(score)

0.17647058823529413
